# Generated by Django 4.0.6 on 2022-11-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_total_votes_project_votes_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Положительный отзыв'), ('down', 'Отрицательный отзыв')], max_length=200),
        ),
    ]
