# Generated by Django 4.0.6 on 2022-12-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_votes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
