# Generated by Django 4.0.6 on 2022-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_total_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='votes_ratio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
