# Generated by Django 4.0.6 on 2022-12-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_project_votes_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
    ]
